CREATE OR REPLACE FUNCTION test()
RETURNS INT AS 'MODULE_PATHNAME', 'test'
LANGUAGE C;

CREATE OR REPLACE FUNCTION scan_pages(rel regclass)
RETURNS VOID AS 'MODULE_PATHNAME', 'scan_pages'
LANGUAGE C STRICT;
